### ISSUE TITLE
Inconsistent Schema in List Data Package Citations Return Values?

### ISSUE THREAD

**Issue by clnsmth** [PASTAplus/PASTA#117]
A user has kindly reported an issue that I have confirmed regarding an unexpected behavior change in the PASTA [List Data Package Citations](https://pastaplus-core.readthedocs.io/en/latest/doc_tree/pasta_api/data_package_manager_api.html#list-data-package-citations) service. This issue pertains to the inconsistency in the schema of the return value for certain elements when they are empty.

For example, consider two citations of the data package knb-lter-hbr.1.15:

```
<journalCitation>
  <journalCitationId>4104</journalCitationId>
  <packageId>knb-lter-hbr.1.15</packageId>
  <principalOwner>uid=EDI,o=EDI,dc=edirepository,dc=org</principalOwner>
  <dateCreated>2023-08-31T13:23:35.620</dateCreated>
  <articleDoi>10.1002/hyp.14961</articleDoi>
  <articleTitle>Estimating uncertainty in streamflow and solute fluxes ...
  <articleUrl>https://onlinelibrary.wiley.com/doi/10.1002/hyp.14961</a ...
  <journalTitle>Hydrological Processes</journalTitle>
  <relationType>IsCitedBy</relationType>
  <pubDate>2023</pubDate>
  <articleAuthors>\n    </articleAuthors>
</journalCitation>
  
<journalCitation>
  <journalCitationId>3725</journalCitationId>
  <packageId>knb-lter-hbr.1.15</packageId>
  <principalOwner>uid=EDI,o=EDI,dc=edirepository,dc=org</principalOwner>
  <dateCreated>2023-05-25T14:22:08.590</dateCreated>
  <articleDoi/>
  <articleTitle>INDIVIDUAL AND POPULATION RESPONSES TO HYDROLOGIC VARIABI ...
  <articleUrl>https://scholarworks.umt.edu/etd/12078</articleUrl>
  <journalTitle>Thesis</journalTitle>
  <relationType>IsCitedBy</relationType>
  <articleAuthors>\n    </articleAuthors>
</journalCitation>
```

- The first citation contains an `<articleDoi>` element with a non-empty value, which is expected.
- The second citation also has the `<articleDoi>` element, but it is empty, which is also expected.
- However, when you examine the `<pubDate>` element, you'll notice that the first citation has it, but the second citation does not. This inconsistency is not expected and is causing issues with code that relies on schema consistency, regardless of whether the element contains an empty value or not.

Any advice you can provide on how to proceed is much appreciated. Thanks!

**Comment by rogerdahl** [comment]
@clnsmth Thank you for writing this up. We definitely want to be consistent, so that missing values can be handled in the same way whenever they occur.

**Comment by clnsmth** [comment]
Thanks for looking into this @rogerdahl. Please let me know if you need additional information.

**Comment by rogerdahl** [comment]
@clnsmth We'll fix this by ensuring that all elements are present in the XML regardless of if there's a value or not. So when there's no value, the element will be included but will be empty (`<element></element>`).

**Comment by clnsmth** [comment]
Thanks for the update @rogerdahl. I think that will work just fine.
