### ISSUE TITLE
Zip archives of data packages should be logged and reported on the data package landing page

### ISSUE THREAD

**Issue by servilla** [PASTAplus/PASTA#123]
Zip archives of data packages should be logged and reported on the data package landing page similar to individual data entities.

**Comment by servilla** [comment]
From @jwbrunt 

> Question about those download numbers - now that you are recording archive downloads will there be a download statistic next to that button on portal or will all the data entities download numbers increment individually?

**Comment by rogerdahl** [comment]
@jwbrunt Yes, we've added a counter that displays next to the zip download button, that counts clicks on that, and that a zip download increases the individual counts on all the data entities that are included in the zip.
