### ISSUE TITLE
Replace UTF-8 0xA0 nbsp with regular space during normalization

### ISSUE THREAD

**Issue by servilla** [PASTAplus/PASTA#126]
Some EML contain non-compliant characters after copying and pasting from other documents, including the UTF-8 code point 0xA0, which is the "nbsp" (non-breaking space) character. Although this character does not cause an issue in its code point form, if it is transformed into the HTML character entity "\&nbsp;" during processing, this specific entity is illegal in XML (it is legal in HTML and used quite regularly). During Level-0-EML to Level-1-EML normalization, the 0xA0 code point is transformed into the "\&nbsp" character entity. Upon further transformation into the Level-1-DC, the XSLT processor fails to perform the transform and complains about the "\&nbsp;" character entity:
>  The entity "nbsp" was referenced, but not declared.

The normalization XSLT should, therefore, replace all 0xA0 code point characters with a simple space (0x20) character.

**Comment by rogerdahl** [comment]
The core issue was that the XSLT transformer was set to output HTML while we were trying to do an XML to XML transform. The commit fixes that and adds replacing non-breaking space with regular space before normalization.
