### ISSUE TITLE
DataPackageManager: Permanently remove /pasta/data/archive directory

### ISSUE THREAD

**Issue by servilla** [PASTAplus/PASTA#134]
The directory `/pasta/data1/archive` that is available from `package.lternet.edu` should be permanently removed from the filesystem. See this issue: https://github.com/PASTAplus/PASTA/issues/133.

Note that this directory is owned by the user `servilla` (probably due to mismatched UIDs when the filesystem was mounted to the updated OS in May 2023). Multiple directories/files in `/pasta/data1` owned by `servilla` also exist that should also be removed. These objects are:
```
find . -user servilla
./INV-GCEM-1208a1.1.0
./abc.100.1
./abc.100.1/evaluate
./abc.100.1/evaluate/quality_report.1365647443317.xml
./channelislandmarine20161128.1.0
./channelislandmarine20161128.1.1
./goofy.txt
```

**Comment by jwbrunt** [comment]
/pasta/data1/archive removed
/pasta/data1/abc.100.1 removed
/pasta/data1/INV-GCEM-1208a1.1.0 removed
/pasta/data1/channelislandmarine20161128.1.1 removed
/pasta/data1/channelislandmarine20161128.1.0 removed
/pasta/data1/goofy.txt removed

In addition:
Ownership on ./lost+found changed from servilla.servilla  to pasta.pasta
/pasta/data1/data1 determined to be a mistake and removed
/pasta/data1/2012-2017MAT89lgcover.2.1 determined to be a mistake and removed

After 24 hours I will check the backup drive and make similar changes if the rsync doesn't clean it up.
