### ISSUE TITLE
handle keywords that include colons?

### ISSUE THREAD

**Issue by twhiteaker** [PASTAplus/PASTA#4]
C:N (carbon to nitrogen ratio) is a variable measured by biologists/ecologists. Querying for that yields "Undefined field C" message, since the colon separates field from value in the Lucene engine.
https://pasta.lternet.edu/package/search/eml?q=C:N&fl=*

Note that eDisMax handles this more gracefully and returns results.
https://pasta.lternet.edu/package/search/eml?q=C:N&fl=*&defType=edismax

**Comment by duanecosta** [comment]
The standard Lucene parser can also handle this query provided that the query value is enclosed in quotes. For example:
    https://pasta.lternet.edu/package/search/eml?q="C:N"&fl=id&rows=1
