### ISSUE TITLE
Design and implement a data package change log for data packages with more than one revision

### ISSUE THREAD

**Issue by servilla** [PASTAplus/PASTA#41]
On Fri, Mar 19, 2021 at 9:57 AM Bashevkin, Sam@DeltaCouncil <Sam.Bashevkin@deltacouncil.ca.gov> wrote:

> Hi Sam,
> 
> We don't currently support a data package change log in the EDI Data Portal, but that is a great idea! We'll have to ponder a bit to get the details just right.
> 
> > As a data publisher, I would love a mechanism to highlight the changes from the last version, whether it’s just adding additional rows with the most recent data, adding additional variables, or changing the structure in some way.
> 
> For an effective data package change log, it seems like we would have to (as you say above) rely on both the metadata provider to clearly indicate what has changed between versions, and then perhaps perform a diff on both the data and metadata to obtain the literal changes of each object. Unfortunately, there is not a dedicated change log section of EML that I am aware of that a data publisher could record this type of information (maybe either <additionalInfo> or a method step <description> for unstructured text or a custom structure in <additionalMetadata>). I will add the general idea of a data package change log as an enhancement ticket in our git repository.
> 
> Thank you for the suggestion, and keep them coming!
> 
> Sincerely,
> Mark
> 
> ---
> Mark Servilla
> mark.servilla@gmail.com
>
> 
>> On Fri, Mar 19, 2021 at 9:57 AM Bashevkin, Sam@DeltaCouncil <Sam.Bashevkin@deltacouncil.ca.gov> wrote:
>> Hello,
>> 
>> I was wondering if EDI had support for a changelog for updated datasets to record all changes to the dataset from the last version. I’m thinking of something analogous to those used in software updates, like this: https://cran.r-project.org/web/packages/dplyr/news/news.html. If this does not yet exist (and I’ve been unable to find it), I would like to request that it be considered as a new feature.
>> 
>> As a data user, integrator, and publisher I think this would be immensely useful and improve the safe use of published data. The biggest problem with maintaining integrated datasets are changes to the underlying datasets which are almost never documented. Each time a dataset is updated, it is a very time-consuming process to ensure the formatting has not changed and my integration code is accurately representing the data structure. For example, I just learned of one EDI dataset that changed units from meters to feet from one update to the next. This is something that would be so much easier to deal with if all changes were documented. As a data publisher, I would love a mechanism to highlight the changes from the last version, whether it’s just adding additional rows with the most recent data, adding additional variables, or changing the structure in some way.
>> 
>> Thank you,
>> 
>> Sam

**Comment by atn38** [comment]
There's dataset/maintenance/changeHistory in EML, which I think the EDI
portal does display. BLE include this info in our revisions, but it's just
free text filled by IMs, not a diff.

**Comment by servilla** [comment]
You are absolutely correct An, the `//maintenance/changeHistory` fits this need quite well - thank you for pointing it out.

**Comment by atn38** [comment]
Hi Mark, I went and looked at the change history display again. I thought that the different history entries could be more spaced out to differentiate between them. e.g. simply adding a little whitespace between the "comment" and the next "scope" boxes would do nicely IMO.
![image](https://user-images.githubusercontent.com/42045942/112361963-eb493980-8ca1-11eb-977a-7b46a764e592.png)

**Comment by servilla** [comment]
Hi An, great suggestion. I'll take a look at the XSLT and see if that whitespace or something similar can be added.

**Comment by servilla** [comment]
Hi An, what do you think of this style:

![image](https://user-images.githubusercontent.com/2224723/112925286-dc61ed00-90ce-11eb-8f55-9861f57b331a.png)

**Comment by atn38** [comment]
That looks great Mark and does the job.
