### ISSUE TITLE
Ensure all data entity data distribution URLs have the function attribute set to download

### ISSUE THREAD

**Issue by servilla** [PASTAplus/PASTA#46]
Ensure all data entity data distribution URLs have the function attribute set to download when creating the Level-1-EML metadata for the data package. This will improve FAIR analysis of the data package when evaluated by EDI and other 3rd party systems.

**Comment by rogerdahl** [comment]
This should modify the EML for any data entity which does not specify "information" or "download" in the URL function attribute, and set it to "download".

**Comment by rogerdahl** [comment]
distribution/online/url/function should be explicitly set to "download" if unset, even though "download" is the default value for function.

**Comment by rogerdahl** [comment]
The existing solution satisfies requirements.
