### ISSUE TITLE
Add EDI ROR to "publisher/userId" element to the Level-1 EML

### ISSUE THREAD

**Issue by servilla** [PASTAplus/PASTA#61]
Add ROR (Research Organization Registry) identifier into the `<publisher>/<userId>` responsibleParty field of the Level-1 EML. The field should use the following pattern:

`<userId directory=" https://ror.org">0330j0z60</userId>`

This is related to #22.

**Comment by servilla** [comment]
During a team meeting on 16 March 2023, a discussion ensued that brought up how RORs (and by extension, ORCIDs) should be stored within the EML metadata under the `<userId>` element:

> One option is to inject the URL prefixed ROR ID in the [level-1 EML generation process](https://github.com/PASTAplus/PASTA/blob/722b4554f75e9f0ac661a6f0a24fffa01bc69261/DataPackageManager/src/edu/lternet/pasta/datapackagemanager/LevelOneEMLFactory.java#L759) thereby making it both machine and human understandable. Inclusion of the URL prefix still retains the PID properties and appears to align with [ROR's recommendations](https://ror.org/about/faqs/#what-is-a-ror-identifier:~:text=The%20preferred%20form%20of%20a%20ROR%20identifier%20is%20the%20entire%20URL%3A%20https%3A//ror.org/02mhbdp94%20rather%20than%20ror.org/02mhbdp94%20or%2002mhbdp94%2C%20although%20the%20ROR%20API%20will%20recognize%20all%20three%20of%20these%20forms%20as%20ROR%20IDs). 
> 
> However, before considering this a solution, a review of DataCite's recommended practices should be done, which at first glance appears to support this pathway via the [nameIdentifiers](https://support.datacite.org/docs/what-is-the-recommended-format-for-including-nameidentifiers-in-the-datacite-metadata) property.

To address this issue, we must first determine the most acceptable form of storing and displaying such information (see https://github.com/PASTAplus/DataPortal/issues/88). We should investigate how DataCite and others who manage such metadata store such information, and see if there are nay  community standards already in place. Key here is that we must decide on differences between how such information is stored versus how such information is displayed.

**Comment by rogerdahl** [comment]
We have decided not to normalize RORs, ORCIDs and any other IDs to a specific format in the EML. Instead, we will add logic to the XSLT to normalize the display of RORs, etc. RORs will be displayed as complete, clickable URLs. If the value in the field is not a URL, we turn it into a URL by prefixing the value of the `directory` attribute.
