### ISSUE TITLE
Event Subscriptions: Open access to Google, GitHub, and ORCiD authenticated users?

### ISSUE THREAD

**Issue by clnsmth** [PASTAplus/PASTA#70]
This generally useful service is only accessible to LDAP authenticated users.  Consider opening access to Google, GitHub, and ORCiD authenticated users.

**Comment by servilla** [comment]
If there are no dependencies on the LDAP DN with regard to the event subscription database and processing, this should only require a change to the ACL for the subscript API POST method.

**Comment by servilla** [comment]
The only modifications necessary were on the Data Portal (see: https://github.com/PASTAplus/DataPortal/commit/f26c2f86bf9acf87de87524319ade680a7c8fcd6). No changes were necessary on PASTA's DataPackageManager service. Changes were pushed out through production as a stable fix.
