### ISSUE TITLE
The List Data Package Citations method drops empty elements

### ISSUE THREAD

**Issue by clnsmth** [PASTAplus/PASTA#76]
The [List Data Package Citations](https://pastaplus-core.readthedocs.io/en/latest/doc_tree/pasta_api/data_package_manager_api.html#list-data-package-citations) method drops empty elements from the XML return. For example, the `journalTitle` element is missing from https://pasta.lternet.edu/package/citations/eml/edi/1103/1.

**Comment by servilla** [comment]
The List Data Package Citations method will not include in the outbound `<journalCitation>` XML any database field that contains a `null` value. `null` values are entered by default when a call to the Create Journal Citation method fails to include a corresponding XML element, even if that element is empty and signified by an empty string. In essence, this is a case of "no garbage in, no garbage out".

Although the above is somewhat a tit-for-tat approach, it would be better to either
1. throw an exception when an incomplete XML recorded is provided (even if some elements are empty), or
2. enter empty strings into all database fields where the element is not provided.

I will implement approach 2 as this will create the least disruption to any users of the existing API.

Note: The journal citation XML should be managed more directly through a schema and corresponding schema validation.

Note: the EDI Data Portal interface forces empty strings for any form element not containing an entered value, thereby satisfying the empty XML element requirement.
