### ISSUE TITLE
Data Package Access Reports display different between Chrome and FIrefox

### ISSUE THREAD

**Issue by servilla** [PASTAplus/PASTA#79]
The User Agent section of the Data Package Access Reports and the paging section of the actual report are different between Chrome and Firefox. They should be "mostly" identical with precedence for Chrome. See below.

Chrome (muy feo):
![image](https://user-images.githubusercontent.com/2224723/163906264-89570c7c-12f2-494c-8c8e-aa9c75f90c19.png)
![image](https://user-images.githubusercontent.com/2224723/163907450-072e298e-bf45-4370-bc71-41aad52cdfbb.png)

Firefox (muy bonito):
![image](https://user-images.githubusercontent.com/2224723/163906366-ecad640b-963e-444e-8c21-b9cf0dcf5ea4.png)
![image](https://user-images.githubusercontent.com/2224723/163907647-3c3f8fd8-c943-4218-873f-5c471c27f0b4.png)

**Comment by rogerdahl** [comment]
Looks like Chrome is not picking up the CSS additions for you. Did you try a Shift+Refresh?
