### ISSUE TITLE
Field delimiter in Read Data Entity Names return object

### ISSUE THREAD

**Issue by clnsmth** [PASTAplus/PASTA#83]
The `Read Data Entity Names` API method returns a new line delimited string with the entity identifier and name separated by a comma. A downstream parsing issue arises when the data entity name itself contains a comma. See: https://github.com/ropensci/EDIutils/issues/38.

**Comment by servilla** [comment]
API documentation (below) is clear that the response contains the entity identifier followed by a comma followed by the entity name. Downstream applications should knowingly split the response using only the first comma as a delimiter in the response payload; subsequent commas, if present, should be interpreted as part of the entity name.

> Message Body: a newline-separated list of lines, where each line contains an entity id followed by a comma followed by the entity name of that entity

**Comment by clnsmth** [comment]
Makes sense. Thanks @servilla.
